# Generated by Django 4.2.7 on 2023-11-06 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=100)),
                ('item_quantity', models.PositiveSmallIntegerField(default=1)),
                ('item_brand', models.CharField(max_length=50, null=True)),
                ('item_grocery_store', models.CharField(choices=[('ALDI', 'Aldi'), ('CONTINENTE', 'Continente'), ('LIDL', 'Lidl'), ('PINGO_DOCE', 'Pingo Doce'), ('INTERMARCHE', 'Intermarche'), ('OUTRO', 'Outro')], max_length=50)),
                ('expected_item_price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STORED', 'Stored')], default='CREATED', max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppinglistitems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('grocery_store', models.CharField(choices=[('ALDI', 'Aldi'), ('CONTINENTE', 'Continente'), ('LIDL', 'Lidl'), ('PINGO_DOCE', 'Pingo Doce'), ('INTERMARCHE', 'Intermarche'), ('OUTRO', 'Outro')], max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(null=True)),
                ('payed_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(max_length=50, null=True)),
                ('min_alert', models.PositiveSmallIntegerField(default=1)),
                ('stockout_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('STORED', 'Stored')], default='CREATED', max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventoryitems', to=settings.AUTH_USER_MODEL)),
                ('shoppinglistitem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.shoppinglistitem')),
            ],
            options={
                'ordering': ['updated'],
            },
        ),
    ]
